//blockchain
export const SET_BLOCKCHAIN = "SET_BLOCKCHAIN";
export const DISCONNECT_BLOCKCHAIN = "DISCONNECT_BLOCKCHAIN";
export const TOGGLE_BLOCKCHAIN_SELECTOR = "TOGGLE_BLOCKCHAIN_SELECTOR";

// cardano wallet
export const CARDANO_SET_WALLET = "CARDANO_SET_WALLET";
export const CARDANO_DISCONNECT_WALLET = "CARDANO_DISCONNECT_WALLET";
export const CARDANO_TOGGLE_WALLET_SELECTOR = "CARDANO_TOGGLE_WALLET_SELECTOR";

// ergo wallet
export const ERGO_SET_WALLET_ADDRESS = "ERGO_SET_WALLET_ADDRESS";
export const ERGO_SET_WALLET_CONNECTED = "ERGO_SET_WALLET_CONNECTED";
export const ERGO_SET_WALLET_NAME = "ERGO_SET_WALLET_NAME";
export const ERGO_SET_IS_MAINNET = "ERGO_SET_IS_MAINNET";
export const ERGO_SET_BALANCE = "ERGO_SET_BALANCE";
export const SIGUSD_SET_BALANCE = "SIGUSD_SET_BALANCE";
export const ERGO_SET_USD_VALUE = "ERGO_SET_USD_VALUE";
export const ERGO_SET_USD_ORACLE = "ERGO_SET_USD_ORACLE";
export const ERGO_SET_WALLET_ASSETS = "ERGO_SET_WALLET_ASSETS";
export const ERGO_SET_EXPLORER_API_CLIENT = "ERGO_SET_EXPLORER_API_CLIENT";
export const ERGO_SET_IS_LOADING = "ERGO_SET_IS_LOADING";
export const ERGO_SET_IS_EYE_OPEN = "ERGO_SET_IS_EYE_OPEN";

export const ERGO_CONNECT_NAUTILUS = "ERGO_CONNECT_NAUTILUS";
export const ERGO_DISCONNECT = "ERGO_DISCONNECT";

//user
export const SIGN_IN = "SIGN_IN";
export const LOGIN = "LOGIN";
export const LOGOUT = "LOGOUT";
export const DELETE_USER_PROFILE = "DELETE_USER_PROFILE";

export const RESET_PASSWORD = "RESET_PASSWORD";
export const SIGNUP = "SIGNUP";
export const FETCH_USER_DATA = "FETCH_USER_DATA";

// fb user
export const LOAD_USER_FROM_STORAGE = "LOAD_USER_FROM_STORAGE";
export const UPDATE_USER_PROFILE = "UPDATE_USER_PROFILE";

export const SET_USER_LENT_LOANS = "SET_USER_LENT_LOANS";
export const SET_USER_BORROWED_LOANS = "SET_USER_BORROWED_LOANS";
export const SET_USER_LENT_LOADING = "SET_USER_LENT_LOADING";
export const SET_USER_BORROWS_LOADING = "SET_USER_BORROWS_LOADING";

//profile activity
export const SET_USER_ACTIVITY = "SET_USER_ACTIVITY";
export const SET_USER_ACTIVITY_LOADING = "SET_USER_ACTIVITY_LOADING";

//user requests
export const SET_USER_REQUESTS_LOADING = "SET_USER_REQUESTS_LOADING";
export const SET_USER_REQUESTS = "SET_USER_REQUESTS";

//modal
export const ModalActionTypes = {
  PUSH_MODAL: "PUSH_MODAL",
  REMOVE_MODAL: "REMOVE_MODAL",
  POP_MODAL: "POP_MODAL",
  CLEAR_STACK: "CLEAR_STACK",
  SHOW_MODAL: "SHOW_MODAL",
  HIDE_MODAL: "HIDE_MODAL",
  TOGGLE_MODAL: "TOGGLE_MODAL",
};

export const LocaleActionTypes = {
  SET_LOCALE: "SET_LOCALE",
};

// Appointments
export const FETCH_MY_APPOINTMENTS_START = "FETCH_MY_APPOINTMENTS_START";
export const FETCH_MY_APPOINTMENTS_SUCCESS = "FETCH_MY_APPOINTMENTS_SUCCESS";
export const FETCH_MY_APPOINTMENTS_FAIL = "FETCH_MY_APPOINTMENTS_FAIL";

export const FETCH_VACANT_APPOINTMENTS_START =
  "FETCH_VACANT_APPOINTMENTS_START";
export const FETCH_VACANT_APPOINTMENTS_SUCCESS =
  "FETCH_VACANT_APPOINTMENTS_SUCCESS";
export const FETCH_VACANT_APPOINTMENTS_FAIL = "FETCH_VACANT_APPOINTMENTS_FAIL";

export const FETCH_WORK_APPOINTMENTS_START = "FETCH_WORK_APPOINTMENTS_START";
export const FETCH_WORK_APPOINTMENTS_SUCCESS =
  "FETCH_WORK_APPOINTMENTS_SUCCESS";
export const FETCH_WORK_APPOINTMENTS_FAIL = "FETCH_WORK_APPOINTMENTS_FAIL";

export const FETCH_CUSTOMER_APPOINTMENTS_START =
  "FETCH_CUSTOMER_APPOINTMENTS_START";
export const FETCH_CUSTOMER_APPOINTMENTS_SUCCESS =
  "FETCH_CUSTOMER_APPOINTMENTS_SUCCESS";
export const FETCH_CUSTOMER_APPOINTMENTS_FAIL =
  "FETCH_CUSTOMER_APPOINTMENTS_FAIL";

export const CLEAR_DRAFT_APPOINTMENT = "CLEAR_DRAFT_APPOINTMENT";
export const SET_DRAFT_APPOINTMENT = "SET_DRAFT_APPOINTMENT";
export const SET_IS_APPOINTMENT_FINISHED = "SET_IS_APPOINTMENT_FINISHED";

export const CREATE_APPOINTMENT_START = "CREATE_APPOINTMENT_START";
export const CREATE_APPOINTMENT_SUCCESS = "CREATE_APPOINTMENT_SUCCESS";
export const CREATE_APPOINTMENT_FAIL = "CREATE_APPOINTMENT_FAIL";

// actions with Requests

export const DELETE_REQUEST_START = "DELETE_REQUEST_START";
export const DELETE_REQUEST_SUCCESS = "DELETE_REQUEST_SUCCESS";
export const DELETE_REQUEST_FAIL = "DELETE_REQUEST_FAIL";

export const ACCEPT_REQUEST_START = "ACCEPT_REQUEST_START";
export const ACCEPT_REQUEST_SUCCESS = "ACCEPT_REQUEST_SUCCESS";
export const ACCEPT_REQUEST_FAIL = "ACCEPT_REQUEST_FAIL";

export const CANCEL_ACCEPT_START = "CANCEL_ACCEPT_START";
export const CANCEL_ACCEPT_SUCCESS = "CANCEL_ACCEPT_SUCCESS";
export const CANCEL_ACCEPT_FAIL = "CANCEL_ACCEPT_FAIL";

export const CLIENT_COMPLAINT_START = "CLIENT_COMPLAINT_START";
export const CLIENT_COMPLAINT_SUCCESS = "CLIENT_COMPLAINT_SUCCESS";
export const CLIENT_COMPLAINT_FAIL = "CLIENT_COMPLAINT_FAIL";

export const FETCH_COMPLAINT_REQUESTS_START = "FETCH_COMPLAINT_REQUESTS_START";
export const FETCH_COMPLAINT_REQUESTS_SUCCESS =
  "FETCH_COMPLAINT_REQUESTS_SUCCESS";
export const FETCH_COMPLAINT_REQUESTS_FAIL = "FETCH_COMPLAINT_REQUESTS_FAIL";
export const CANCEL_ACCEPT_PSYCHE = "CANCEL_ACCEPT_PSYCHE";
export const CONFIRM_APPOINTMENT_ON_CHAIN = "CONFIRM_APPOINTMENT_ON_CHAIN";
export const PSYCH_CLAIMS_REWARDS = "PSYCH_CLAIMS_REWARDS";
export const INCREMENT_HR_PSY = "INCREMENT_HR_PSY";
export const INCREMENT_HR_IN_PSY = "INCREMENT_HR_IN_PSY";

// Appointment room
export const SET_REQUEST_ROOM_ID = "SET_REQUEST_ROOM_ID";
export const SET_REQUEST_ROOM = "SET_REQUEST_ROOM";
export const UPDATE_REQUEST_ROOM = "UPDATE_REQUEST_ROOM";
export const CLEAN_REQUEST_ROOM = "CLEAN_REQUEST_ROOM";

export const SEND_MESSAGE_SUCCESS = "SEND_MESSAGE_SUCCESS";
export const SEND_MESSAGE_FAILURE = "SEND_MESSAGE_FAILURE";

// Calls
export const SHOW_VIDEO_CALL = "SHOW_VIDEO_CALL";
export const HIDE_VIDEO_CALL = "HIDE_VIDEO_CALL";

// Saving freeTime slots for users
export const SAVE_SLOTS_REQUEST = "SAVE_SLOTS_REQUEST";
export const SAVE_SLOTS_SUCCESS = "SAVE_SLOTS_SUCCESS";
export const SAVE_SLOTS_FAILURE = "SAVE_SLOTS_FAILURE";

// Specialists
export const FIND_SPECIALISTS_REQUEST = "FIND_SPECIALISTS_REQUEST";
export const FIND_SPECIALISTS_SUCCESS = "FIND_SPECIALISTS_SUCCESS";
export const FIND_SPECIALISTS_FAILURE = "FIND_SPECIALISTS_FAILURE";
export const SET_SELECTED_SPECIALIST = "SET_SELECTED_SPECIALIST";

export const FIND_SPECIALISTS_BY_NICK_REQUEST = "FIND_SPECIALISTS_REQUEST";
export const FIND_SPECIALISTS_BY_NICK_SUCCESS = "FIND_SPECIALISTS_SUCCESS";
export const FIND_SPECIALISTS_BY_NICK_FAILURE = "FIND_SPECIALISTS_FAILURE";
export const SET_SELECTED_BY_NICK_SPECIALIST = "SET_SELECTED_SPECIALIST";

export const CLEAR_SPECIALIST_LIST = "CLEAR_SPECIALIST_LIST";

export const FIND_RANDOM_SPECIALISTS_REQUEST =
  "FIND_RANDOM_SPECIALISTS_REQUEST";
export const FIND_RANDOM_SPECIALISTS_SUCCESS =
  "FIND_RANDOM_SPECIALISTS_SUCCESS";
export const FIND_RANDOM_SPECIALISTS_FAILURE =
  "FIND_RANDOM_SPECIALISTS_FAILURE";

// ADMIN ACTIONS ==========================
//
// Job Applications
export const FETCH_JOB_APPLICATIONS = "FETCH_JOB_APPLICATIONS";
export const FETCH_JOB_APPLICATIONS_ERROR = "FETCH_JOB_APPLICATIONS_ERROR";

export const FETCH_COMPLAINTS = "FETCH_COMPLAINTS";
export const FETCH_COMPLAINTS_ERROR = "FETCH_COMPLAINTS_ERROR";

export const TOGGLE_LOADING = "TOGGLE_LOADING";
export const SET_SELECTED_JOB_APPLICATION = "SET_SELECTED_JOB_APPLICATION";

export const UPDATE_JOB_APPLICATION_REQUEST = "UPDATE_JOB_APPLICATION_REQUEST";
export const UPDATE_JOB_APPLICATION_SUCCESS = "UPDATE_JOB_APPLICATION_SUCCESS";
export const UPDATE_JOB_APPLICATION_FAILURE = "UPDATE_JOB_APPLICATION_FAILURE";

// POSTS
export const GET_POST_BY_ID_SUCCESS = "GET_POST_BY_ID_SUCCESS";
export const GET_POST_BY_ID_ERROR = "GET_POST_BY_ID_ERROR";
export const SET_SELECTED_POST = "SET_SELECTED_POST";
export const SET_EDIT_POST = "SET_EDIT_POST";

export const DELETE_POST_SUCCESS = "DELETE_POST_SUCCESS";
export const DELETE_POST_ERROR = "DELETE_POST_ERROR";

export const UPDATE_POST_CLAPS = "UPDATE_POST_CLAPS";

export const CREATE_POST_SUCCESS = "CREATE_POST_SUCCESS";
export const CREATE_POST_ERROR = "CREATE_POST_ERROR";
export const UPDATE_POST_SUCCESS = "UPDATE_POST_SUCCESS";
export const UPDATE_POST_ERROR = "UPDATE_POST_ERROR";

export const FETCH_POSTS = "FETCH_JOB_APPLICATIONS";
export const FETCH_POSTS_ERROR = "FETCH_JOB_APPLICATIONS_ERROR";

export const ADD_COMMENT_SUCCESS = "ADD_COMMENT_SUCCESS";
export const ADD_COMMENT_ERROR = "ADD_COMMENT_ERROR";
export const DELETE_COMMENT_SUCCESS = "DELETE_COMMENT_SUCCESS";
export const DELETE_COMMENT_ERROR = "DELETE_COMMENT_ERROR";

// ADMIN dealing with USERS ==========================

export const CREATE_NEW_USER = "CREATE_NEW_USER";
export const SET_APPLICANT_USER_DATA = "SET_APPLICANT_USER_DATA";

// Events
export const FETCH_EVENTS_REQUEST = "FETCH_EVENTS_REQUEST";
export const FETCH_EVENTS_SUCCESS = "FETCH_EVENTS_SUCCESS";
export const FETCH_EVENTS_FAILURE = "FETCH_EVENTS_FAILURE";

export const FETCH_MY_EVENTS_REQUEST = "FETCH_MY_EVENTS_REQUEST";
export const FETCH_MY_EVENTS_SUCCESS = "FETCH_MY_EVENTS_SUCCESS";
export const FETCH_MY_EVENTS_FAILURE = "FETCH_MY_EVENTS_FAILURE";

export const SET_SELECTED_EVENT = "SET_SELECTED_EVENT";

export const SHOW_EVENT_ROOM = "SHOW_EVENT_ROOM";
export const HIDE_EVENT_ROOM = "HIDE_EVENT_ROOM";
export const ADD_EVENT_PARTICIPANT = "ADD_EVENT_PARTICIPANT";
export const REMOVE_EVENT_PARTICIPANT = "REMOVE_EVENT_PARTICIPANT";
export const REMOVE_EVENT_PARTICIPANT_ROLLBACK =
  "REMOVE_EVENT_PARTICIPANT_ROLLBACK";

export const DELETE_EVENT_REQUEST = "DELETE_EVENT_REQUEST";
export const DELETE_EVENT_SUCCESS = "DELETE_EVENT_SUCCESS";
export const DELETE_EVENT_FAILURE = "DELETE_EVENT_FAILURE";
export const FINISH_EVENT_SUCCESS = "FINISH_EVENT_SUCCESS";
